# Site info
title: Steve for Jekyll
tagline: Charming and fun blog theme.
description: Steve is a charming and fun blog theme for Jekyll websites.

email: steve-support@esporo.net

lang: en

url: ""
baseurl: ""

# Theme settings
steve:
  intensedebate_account: # get one at <https://intensedebate.com/install>
  archives: # Prefixes used with archive titles
    date: Posts from
    tag: More about…
    category: Posts filed in
  date_formats: # Uses <http://strftime.net>
    post: "%b %e, %Y"
    archives:
      day: "%b %e, %Y"
      month: "%b, %Y"
      year: "%Y"
  page_404: |+
    The page you're looking for could not be found.

    Maybe the search can help.
  pagination:
    next_page: "&laquo; Next"
    prev_page: "Previous &raquo;"
    prev_post: "Previous:"
    next_post: "Next:"
  post:
    byline: "By"
    tags: More about…
  search:
    label: Search this blog
    placeholder: What you're looking for?
    submit: Go!


# Build settings
markdown: kramdown
permalink: "/:year/:month/:day/:title/"

theme: steve-for-jekyll

paginate: 6
paginate_path: "/page/:num/"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-archives

# Plugin: jekyll-archives
jekyll-archives:
  enabled: all
  layout: archive
  slug_mode: default
  permalinks:
    day: "/:year/:month/:day/"
    month: "/:year/:month/"
    year: "/:year/"
    category: "/:name/"
    tag: "/tag/:name/"
