# Site info
title: Steve for Jekyll
tagline: Charming and fun blog theme.
description: Steve is a charming and fun blog theme for Jekyll websites.

email: steve-support@esporo.net

lang: en

url: ""
baseurl: "/steve/"

# Theme settings
steve:
  archives: # Prefixes used with archive titles
    date: Posts from
    tag: More about…
    category: Posts filed in
  date_formats: # Uses <http://strftime.net>
    post: "%b %e, %Y"
    archives:
      day: "%b %e, %Y"
      month: "%b, %Y"
      year: "%Y"
  page_404: |+
    The page you're looking for could not be found.

    Maybe the search can help.
  pagination:
    next_page: "&laquo; Next"
    prev_page: "Previous &raquo;"
    prev_post: "Previous:"
    next_post: "Next:"
  post:
    byline: "By"
    tags: More about…
  search:
    label: Search this blog
    placeholder: What you're looking for?
    submit: Go!

# Comments Settings
comments:
  title: Comments
  form_title: New Comment
  date_format: "%b %e, %Y @ %l:%M %P"
  staticman_endpoint: # Get yours on <https://staticman.net>
  notice: |+
    Please be nice in the comments.

    Comments are moderated, so it can take a while for your's to show up.

    Also, you can use [Markdown](https://daringfireball.net/projects/markdown).
  fields:
    name:
      label: Name
      placeholder: "John Appleseed"
    email:
      label: Email address
      placeholder: "your@email.net"
    website:
      label: Website
      placeholder: "https://john.blog/"
    message:
      label: Message
      placeholder: Your comment message
    submit: Submit Comment


# Build settings
markdown: kramdown
permalink: "/:year/:month/:day/:title/"

theme: steve-for-jekyll

paginate: 6
paginate_path: "/page/:num/"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-archives

# Plugin: jekyll-archives
jekyll-archives:
  enabled: all
  layout: archive
  slug_mode: default
  permalinks:
    day: "/:year/:month/:day/"
    month: "/:year/:month/"
    year: "/:year/"
    category: "/:name/"
    tag: "/tag/:name/"
