# Site info
title: Steve for Jekyll
tagline: Charming and fun blog theme.
description: Steve is a charming and fun blog theme for Jekyll websites.

email: steve-support@esporo.net

lang: en

url: ""
baseurl: "/steve"

# Build settings
markdown: kramdown
permalink: "/:year/:month/:day/:title/"

theme: steve-for-jekyll

paginate: 12
paginate_path: "/page/:num/"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-archives

# Plugin: jekyll-archives
jekyll-archives:
  enabled: all
  layout: archive
  slug_mode: default
  permalinks:
    day: "/:year/:month/:day/"
    month: "/:year/:month/"
    year: "/:year/"
    category: "/:name/"
    tag: "/tag/:name/"
