# Site info
title: Steve for Jekyll
tagline: Charming and fun blog theme.
description: Steve is a charming and fun blog theme for Jekyll websites.

email: steve-support@esporo.net

lang: en-US

# Build settings
markdown: kramdown
permalink: "/:year/:month/:day/:title/"

paginate: 6
paginate_path: "/page/:num/"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
