# Site info
title: Steve for Jekyll
tagline: Charming and fun blog theme.
description: Steve is a charming and fun blog theme for Jekyll websites.

email: steve-support@esporo.net

lang: en

url: "https://esporo.github.io"
baseurl: ""

# Theme settings
steve:
  intensedebate_account: # get one at <https://intensedebate.com/install>
  archive_title:
    date: "Posts from"
    tag: "More about"
    category: "Category:"
  date_formats:
    archive:
      day: "%m/%d/%Y"
      month: "%m/%Y"
      year: "%Y"
    post: "%m/%d/%Y"

# Build settings
markdown: kramdown
permalink: "/:year/:month/:day/:title/"

paginate: 2
paginate_path: "/page/:num/"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-archives

# Plugin: jekyll-archives
jekyll-archives:
  enabled: all
  layout: archive
  slug_mode: default
  permalinks:
    day: "/:year/:month/:day/"
    month: "/:year/:month/"
    year: "/:year/"
    category: "/:name/"
    tag: "/tag/:name/"
